package Timekeeping.editor;

/*Generated by MPS */


public class FontSizeScaler {
  public static int small() {
    return 14;
  }
  public static int medium() {
    return 18;
  }

  public static int medium_large() {
    return 22;
  }

  public static int large() {
    return 28;
  }
}
