package Timekeeping.editor;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class INTL {
  public static String getLanguage() {
    return "de";
  }
  public static String getString(String key) {
    Map<String, String> month = MapSequence.fromMap(new HashMap<String, String>());
    MapSequence.fromMap(month).put("de", "Monat");
    MapSequence.fromMap(month).put("en", "month");

    Map<String, String> day = MapSequence.fromMap(new HashMap<String, String>());
    MapSequence.fromMap(day).put("de", "Tag");
    MapSequence.fromMap(day).put("en", "day");

    Map<String, Map<String, String>> strings = MapSequence.fromMap(new HashMap<String, Map<String, String>>());
    MapSequence.fromMap(strings).put("day", day);
    MapSequence.fromMap(strings).put("month", month);

    return MapSequence.fromMap(MapSequence.fromMap(strings).get(key)).get(getLanguage());
  }
}
